### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#10]
¿Alguien se anima a hacer un logo?

**Comment by JuanMatSa** [comment]
Veo que se me ha asignado... Subiré las ideas que tuve, pero cualquier
sugerencia es bienvenida :)


El lunes, 21 de diciembre de 2015, Álex Sáez <notifications@github.com>
escribió:

> Assigned #10 <https://github.com/AeroPython/PyFME/issues/10> to @JuanMatSa
> <https://github.com/JuanMatSa>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AeroPython/PyFME/issues/10#event-497861569>.
>


-- 
--------------------------------------------------------------------------------------------------------------------
Juan José Matesanz Saiz
Aerospace Engineer
+34 665 954 756
juan.matesanz.saiz@gmail.com

**Comment by Juanlu001** [comment]
Si me visitan las musas subo algo :)

**Comment by JuanMatSa** [comment]
bueno, algunos diseños que he ido haciendo... 
están a mano sí pero a lo mejor de ahí sacamos los: no me gusta ninguno, me gusta algo este, o espera que tengo una idea a partir de uno de ellos. mojaros, y despachaos a gusto (no soy diseñador gráfico, que me digáis que no os mola no me va a deprimir =D)

un saludo y feliz comiendo de vacaciones
![img_20151222_201056391 1](https://cloud.githubusercontent.com/assets/16115857/11964378/903fc920-a8ed-11e5-8357-fb9d844b9593.jpg)
![img_20151222_201104948 1](https://cloud.githubusercontent.com/assets/16115857/11964404/b7560268-a8ed-11e5-8888-ab0d6bf227a2.jpg)
![img_20151222_201108728 1](https://cloud.githubusercontent.com/assets/16115857/11964441/18fae916-a8ee-11e5-87ee-b1e889a3f857.jpg)
![img_20151222_201116459 1](https://cloud.githubusercontent.com/assets/16115857/11964465/456a5dc4-a8ee-11e5-8ca8-a01d166a1eb8.jpg)

**Comment by JuanMatSa** [comment]
![img_20151222_201206144 1](https://cloud.githubusercontent.com/assets/16115857/11964584/10b85008-a8ef-11e5-9011-9f4703022ef1.jpg)
![img_20151222_201158303 1](https://cloud.githubusercontent.com/assets/16115857/11964585/11dbde6e-a8ef-11e5-9769-711b89d4821e.jpg)
![img_20151222_201150878 1](https://cloud.githubusercontent.com/assets/16115857/11964612/43703f92-a8ef-11e5-8e82-9ee929c3e27c.jpg)
![img_20151222_201144436 1](https://cloud.githubusercontent.com/assets/16115857/11964616/47ae2a38-a8ef-11e5-8ca6-312af8ff07b9.jpg)
![img_20151222_201116459 1](https://cloud.githubusercontent.com/assets/16115857/11964620/4c39e984-a8ef-11e5-9cb1-f478bf1c650e.jpg)

**Comment by Juanlu001** [comment]
Me gusta mucho la idea de los aviones y la "estela", y el antepenúltimo, el del avión de papel, el que más. Esta semana intento darle una pasadita en Inkscape.

**Comment by olrosales** [comment]
A mi el del avión de papel me gusta, pero también  me gusta la idea de los instrumentos de navegación

**Comment by olrosales** [comment]
Tengo una foto de una bastón bola pero no puedo subirla desde el movil

**Comment by olrosales** [comment]
Se que está muy mal hecho, pero yo propongo algo así,
![logo_1](https://cloud.githubusercontent.com/assets/10099468/11984428/739d37c0-a9bb-11e5-99a7-992efa2a24f7.png)

**Comment by Juanlu001** [comment]
Se ve un poco mal Óscar, es un "bastón y bola" ¿no? Enlaza por aquí si tienes alguna fotillo que sirva de inspiración.

**Comment by AlexS12** [comment]
A mí me gusta bastante el avión de papel con la estela y también me molaría algo de este estilo:

![logo_1](http://www.commons.thetangentbundle.net/w/images/thumb/Euler_angles_phi_theta_psi.svg/300px-Euler_angles_phi_theta_psi.svg.png) con un avioncito superpuesto o algo así.

**Comment by olrosales** [comment]
Me gusta mucho la idea de Añex

**Comment by AlexS12** [comment]
Estuve jugando un poco el otro día intentando hacer un logo.

![image](https://cloud.githubusercontent.com/assets/6061587/12182539/1014629e-b589-11e5-8044-0d4a0440e273.png)

Os dejo el link al svg: https://www.dropbox.com/s/zd092b7b0u0mflg/drawing.svg?dl=0
Por cierto, el avión no es mío... Es una imagen vectorial libre.

**Comment by Juanlu001** [comment]
La versión 0.1 tendrá que tener su logo :)

**Comment by Juanlu001** [comment]
Puedo prometer y prometo que PyFME v0.1 tendrá logo.

**Comment by Juanlu001** [comment]
¿Qué os parece? Basado en la idea de @JuanMatSa :grin:

![logo2_alt](https://cloud.githubusercontent.com/assets/316517/20037645/2f19947c-a424-11e6-9612-bf2871206f29.png)
