### ISSUE TITLE
geopotential height vs. geometric height

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [AeroPython/PyFME#110]
I've noticed that the `atmosphere` class uses geopotential height rather than geometric height.  I'm assuming that you are following the definition of geopotential height given here:

https://en.wikipedia.org/wiki/Geopotential_height

It seems to me that geometric height would be far more convenient for a user.

**Comment by AlexS12** [comment]
Hi @Phillip-M-Feldman, you can check the conversions in: https://github.com/AeroPython/PyFME/blob/master/src/pyfme/utils/altimetry.py 
It is true that the user is much more used to geometric heights, however ISA is formulated under the hypothesis of constant gravity=g0, thats why `atmosphere` uses geopotential. In any case, differences are small for a normal airplane.

I am closing the issue. Just let us know if you need any other clarification.

**Comment by Phillip-M-Feldman** [comment]
This is helpful, but I have two follow-up questions:

What does "ISA" stand for?

What is meant by the term "normal airplane"?

Phillip

**Comment by AlexS12** [comment]
Hi @Philip-m-Feldman, ISA stands for International Standard Atmosphere. This link might be a good introduction https://en.m.wikipedia.org/wiki/International_Standard_Atmosphere?wprov=sfti1

By normal plane I meant the height at which a commercial aircraft flies
