### ISSUE TITLE
Help my

### ISSUE THREAD

**Issue by loywer** [AeroPython/PyFME#121]
Hello, can you please share the initial data for aerodynamics cessna 172. For my project, thank you in advance.

**Comment by AlexS12** [comment]
@ghost, you can check the data in this file: https://github.com/AeroPython/PyFME/blob/master/src/pyfme/aircrafts/cessna_172.py

The coefficients were obatined from the references that you can find in the doc: https://github.com/AeroPython/PyFME/blob/master/src/pyfme/aircrafts/cessna_172.py#L10

Hope it helps!
