### ISSUE TITLE
Funciones Anemometry

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#19]
Pronto necesitaremos algunas funciones nuevas. 

Podemos hacer un nuevo paquete dentro de `utils` que se llame, si os parece adecuado, `anemometry.py` y que contenga funciones relacionadas con velocidades aerodinámicas. Creo que cuadra más en `utils` que en `environment` porque son funciones genéricas y no modelos físicos (como una atmósfera, una ráfaga, un modelo gravitatorio...).

De momento, es previsible que hagan falta (hay que elegir también los nombres):

* [x] __Cálculo de ángulo de ataque (alpha), de resbalamiento (betha) y velocidad verdadera (TAS) a partir de las velocidades con respecto al viento__. De momento no hay ningún tipo de viento en el simulador (las velocidades con respecto a tierra coinciden con respecto a las aerodinámicas), más adelante incorporaremos vientos y habrá que tener en cuenta el darle a cada función los inputs que correspondan (la cosa se complicará más cuando planteemos las ecuaciones el sistema geocéntrico inercial...). Los inputs por tanto podrían ser la velocidad con respecto a tierra en ejes cuerpo y las velocidades del viento en ejes cuerpo (fijadas a cero por defecto).

* [ ] __Cálculo del número de Mach a partir de la velocidad aerodinámica y la altura__. Llamará a la ISA por debajo. Otra opción sería llamar a la ISA antes y pasar la velocidad del sonido en vez de la altura. Tendría la ventaja de que sería más fácil cambiar de atmósfera luego... ¿opiniones?

* [x] __Cálculo de la presión dinámica__ (q_inf) a partir de:
     - la densidad y la velocidad aerodinámica (TAS).
     - ~~la presión y el número de Mach~~. Como implica andar pasando el gamma (que es un parámetro de la atmósfera) y en principio siempre vamos a tener la TAS de momento la dejo en el aire y nos quedamos con la primera sólo.

* [ ] __Cálculo de la velocidad del sonido (a_inf) en función de la altura__. La necesita la función anterior, ¿la metemos en la ISA o en anemometry?.

---
Otras:

* [ ] Cálculo de la altitud presión.
* [ ] Cálculo de CAS y EAS.
* ¿ideas?

---
 
__¿Quién se anima?__

![image](https://cloud.githubusercontent.com/assets/6061587/12091024/168e697c-b2f4-11e5-8f7c-3120342cfada.png)

**Comment by Juanlu001** [comment]
Cerrado con #44.
