### ISSUE TITLE
Consistencia en las cabeceras de las funciones - pasar arrays o números

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#21]
De momento no pasa nada (lo pongo para aquí para acordarnos), pero para la siguiente vez que nos juntemos deberíamos llegar a un acuerdo sobre como pasar los argumentos que son vectores, si como arrays o por cada una de sus componentes. De momento tenemos ejemplos de ambas:

    linear_and_angular_momentum_eqs(time, vel, mass, inertia, forces, moments)

    body2hor(body_coords, theta, phi, psi)

otra opción más avanzada, como comentaba @Juanlu001 en el grupo de Telegram, sería hacer algo parecido a lo que hace SymPy o usarlo directamente.

**Comment by AlexS12** [comment]
El consenso es que siempre que sea posible pasaremos los vectores, en lugar de las componentes. ls nombres recomendados son:

lin_vel = (u, v, w)
ang_vel = (p, q, r)
pos = (x, y, z)
attitude = (theta, phi, psi)

alpha y beta se pasarán separados

**Comment by Juanlu001** [comment]
¡Esto merece una entrada en la wiki también!

**Comment by AlexS12** [comment]
Ok! Me lo apuntó. Reabro el issue para acordarme, igual requiere cambiar cosas en código. Echaré un vistazo también!

**Comment by Juanlu001** [comment]
Esto merece una entrada en la wiki @AlexS12 :wink:

**Comment by AlexS12** [comment]
Esto afectaría fundamentalmente a las funciones que hicimos al principio del simulados. Ahora, la verdad es que usando poo y pasando las clases que os enseñé por cabecera, se simplifica bastante el tema.

Me apunto la entrada en la wiki! :+1:

**Comment by Juanlu001** [comment]
Supongo que esto está relacionado con #41, ¿qué opináis?

**Comment by AlexS12** [comment]
Sí, yo creo que vamos a cerrar este y dejamos el otro abierto para no olvidarnos
