### ISSUE TITLE
Definición de dependencias

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#25]
De momento creo que no es un problema, pero estaría bien para evitar sorpresas, definir el entorno que tenemos que configurar en conda para trabajar todos con los mismos paquetes.

**Comment by Juanlu001** [comment]
Lo que podemos hacer es subir un archivo `environment.yml` que reconstruya el entorno conda:

http://conda.pydata.org/docs/using/envs.html#export-the-environment-file

Podríamos acordar trabajar todos en Python 3.5 y dejar que Travis ejecute los tests en otras versiones, por ejemplo.

**Comment by Juanlu001** [comment]
O de esta otra forma, que es un poco más flexible y puede servir para reutilizarlo en el entorno de integración continua:

http://conda.pydata.org/docs/using/envs.html#build-identical-conda-environments

**Comment by AlexS12** [comment]
Pues si la segunda nos puede venir mejor, podemos decantarnos por esa. ¿Qué opinas?

**Comment by Juanlu001** [comment]
Nótese que he hecho referencia a este issue desde un commit. Incluyendo `fixes #NN` en el mensaje, en cuanto se fusione la pull request se cerrará automáticamente esta tarea. Magic! :dizzy:

**Comment by Juanlu001** [comment]
Por cierto, para futuras referencias: la creación de entornos con archivos `environment.yml` está un poco mal documentada (haciendo pruebas he visto que son más flexibles de lo que yo pensaba) y de hecho puede que en el futuro eliminen el comando `conda env` (se lo he leído a Mike Sarahan, de Continuum, en algún comentario pero ahora no lo encuentro). De momento ver #42 para más detalles.

**Comment by AlexS12** [comment]
Vale, estupendo! Gracias @Juanlu001 buena información!

Woow! lo de fixes me ha matado: https://help.github.com/articles/closing-issues-via-commit-messages/
