### ISSUE TITLE
Tutorial paso a paso del flujo de trabajo

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#26]
Tarea de documentación que igual nos resulta útil. Id rellenándolo, yo iré añadiendo cosas cuando vaya teniendo algún rato. Igual esto sirve de inspiración: http://suave.stanford.edu/develop/

Aquí la página de la wiki que queremos ir completando:
https://github.com/AeroPython/PyFME/wiki/Tutorial-paso-a-paso-del-flujo-de-trabajo

**Comment by AlexS12** [comment]
¡Cerramos cuando esté completo en la wiki!

**Comment by JuanMatSa** [comment]
qué sería bueno poner de git? todas las opciones que tiene add commit...? yo creo que no hay mejor explicación que la de gitinmmersion, pero puedo ponerlo un poco resumido con los pantallazos del propio git

**Comment by AlexS12** [comment]
@JuanMatSa No te compliques demasiado. git status, git add, git commit, git checkout y poco más..
Usa de ejemplo algún caso que hayas hecho y ya está

**Comment by AlexS12** [comment]
Veo que no ha habido cambios en la wiki aquí. Lo dejo abierto!

**Comment by AlexS12** [comment]
He añadido un link a http://gitimmersion.com/lab_04.html en la parte sobre add, commit, status... con las lecciones correspondientes. ¡Podemos darlo por cerrado!
