### ISSUE TITLE
Error tipográfico en `check_theta_phi_psi_range`

### ISSUE THREAD

**Issue by Juanlu001** [AeroPython/PyFME#31]
La variable `psi` no se está comprobando:

https://github.com/AeroPython/PyFME/blob/11fc5865f/src/pyfme/utils/coordinates.py#L24

Hay que corregir el error y añadir los tests correspondientes.

**Comment by JuanMatSa** [comment]
abro rama, lo cambio y pusheo

**Comment by AlexS12** [comment]
pull req #34
