### ISSUE TITLE
Altimetría

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#38]
La altitud que entra en la isa es la geopotencial. Se me ocurre que quizá esté bien tener dentro del paquete utils, un módulo `altimetry.py` que se encargue de conversiones de altitud.

* Altitud geométrica (h): sería la distancia al centro de la tierra menos el radio (medio) de la tierra.
* Altitud barométrica: es la altitud que en la atmósfera estándar corresponde al valor de presión que lee el barómetro del avión en vuelo.
* Altitud geopotencial (H): es la altitud geométrica considerando la gravedad constante. Para obtener la geométrica a la que corresponde: se busca la altitud (geométrica y con gravedad dependiente de la altura) que tiene el mismo potencial que la altitud geopotencial dada. Acaba siendo: h = r_t * H / (r_t - H)

Podemos ir implementando el módulo con conversiones del estilo: `geopotential2geométrical(h)`...

**Comment by DLpadilla** [comment]
Yo me quedo con este issue. Si os parece bien.

**Comment by Juanlu001** [comment]
@DLpadilla 👌

**Comment by AlexS12** [comment]
Estupendo! había pensado en ti!

**Comment by AlexS12** [comment]
Se puede cerrar esto con lo que subió ayer Dani! Pull request #55
