### ISSUE TITLE
Nuevas clases: tests y documentación

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#70]
Como a raíz de #65 se introdujeron una serie de clases: `Simulation`, `System`, `Aircraft`, `Environment`, `Gravity`, `Wind`, `Atmosphere` convendría hacer una serie de tests unitarios para garantizar que la cadena de "`.update()`" funciona ahora y sigue funcionando cuando toquemos cosas.

Como esta parte es complicada para quien acabe de llegar, me asigno la tarea y de paso documento las cosas que quedaron pendientes. Si jugáis con el código y veis que falta documentación o no está bien en algún lado, ponedlo por aquí porfa :smiley: (o cambiadlo vosotros mismos si os veis con ganas!).

**Comment by Juanlu001** [comment]
De hecho, hay algunas partes de la documentación que están desactualizadas, como aquí que aún se importa `pyfme.environment.isa`:

https://github.com/AeroPython/PyFME/blob/ab4cc0f4/docs/source/api.rst

Lo he visto en los logs de Read The Docs:

http://readthedocs.org/projects/pyfme/builds/4336976/
