### ISSUE TITLE
Incluir la evolución temporal de las deflexiones en las gráficas de salida

### ISSUE THREAD

**Issue by aqreed** [AeroPython/PyFME#85]
Sería interesante que de output se obtuviera una décima gráfica donde se pueda ver la posición, en grados, de las 3 deflexiones y la posición del throttle también.

**Comment by AlexS12** [comment]
Buena idea! Me parece guay, voy a pasar esto a #58 para tenerlo todo junto porque es un tema a abordar ahí. En realidad en los ejemplos está hecho de un modo artesano y provisional.
