### ISSUE TITLE
Functions documentation

### ISSUE THREAD

**Issue by sanguinariojoe** [AeroPython/PyFME#87]
line 81 of src/pyfem/aircrafts/aircraft.py, among others (many of them).

Please, conveniently document the functions, and more specifically the parameters and returned values. That would significantly improve the code readability (without need to look for the calls to the function).

**Comment by aqreed** [comment]
@AlexS12 @Juanlu001 how would we define what the [function](https://github.com/AeroPython/PyFME/blob/master/src/pyfme/aircrafts/aircraft.py#L81) `update` does?
