### ISSUE TITLE
Atmósfera ISA

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/PyFME#9]
Esto hereda del trabajo que comenzamos hace ya tiempo. Ver https://github.com/AeroPython/aeropy/tree/master/aeropy/atmosphere ¿Vamos a utilizar ese paquete o vamos a ir definiendo esas cosas a parte?

En este caso, no necesitaríamos trabajar con arrays de alturas, porque en cada paso de integración tendremos sólo una altura. El número de capas también puede ser menor.

**Comment by Juanlu001** [comment]
Esta me la asigno yo porque tengo tareas pendientes en ese repositorio. De todos modos sigue habiendo algunos asuntos sin resolver (https://github.com/AeroPython/aeropy/issues/8).

No hicimos benchmarks con muchas capas, pero en todo caso se podría proporcionar una versión completa (con todas las que aparecen en el estándar) y otra rápida (con las que hagan falta para aviones comerciales normales).
