### ISSUE TITLE
Plot Upgrades

### ISSUE THREAD

**Issue by salgozino** [AeroPython/PyFME#92]
I have some idea to upgrade in the plots that the simulations output.

- I think that is important to plot the evolution of the deflection angles of the commands to understand why are changing all the other variables.

- The units in the plot are importants. I guess that the angles are in radians, the forces and moments are in Newtons and N.m but it's just a suposition due to the order of magnitude of the values. The coordinates in Earth are in meters?

**Comment by AlexS12** [comment]
Hi @salgozino, thanks for the issue.

You are right! in the near future, one of the main tasks should be implementing a module to deal with the outputs properly. As you have mentioned it would be interesting to plot some other variables and right now, there is no obvious and easy way to do it. 

Of course, units, titles and legends are fundamental.  Answering your question, forces are expressed in N and moments in N·m :wink:

**Comment by aeroaks** [comment]
I would be interested working on this! though would need clarity on the desired result!

**Comment by AlexS12** [comment]
Conversation will continue in #58
